//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationCourses.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentId { get; set; }
        public int RegistrationId { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMethod { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string CardNumber { get; set; }
        public string ExpiryDate { get; set; }
        public string CVV { get; set; }
    
        public virtual Registrations Registrations { get; set; }
    }
}
